-- =============================================================
-- MonBonAgent — Cleanup 16 démos Perpignan + Seed 84 réels Elne
-- Source : data/commerces-elne.json (OSM ODbL + Sirene Licence ouverte)
-- Status = 'directory' : annuaire local, non partenaire actif
-- =============================================================

begin;

-- 1) Cleanup : 6 offres + 16 commerçants démos Perpignan
delete from public.offers where merchant_id in (select id from public.merchants);
delete from public.merchants;

-- 2) Seed : insertion des commerces réels d'Elne (annuaire OSM + Sirene)
insert into public.merchants (name, category, address, phone, website, image_url, description, status, slug, featured, rating, avis, hours, created_at) values
  ('Al Sima', 'Alimentation', 'Boulevard Jacques Albert, 66200 Elne', '+33 4 68 64 52 19', 'https://www.al-sima.fr/magasin/elne/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'al-sima', false, null, null, null, now()),
  ('AUDIAL', 'Santé & bien-être', '1 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'audial', false, null, null, null, now()),
  ('AYMERIC FERRER', 'Services', '19 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'aymeric-ferrer', false, null, null, null, now()),
  ('FREDERIC VICENTE', 'Restaurants', '6 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'frederic-vicente', false, null, null, null, now()),
  ('FVMG', 'Alimentation', 'Bd Jacques Albert Route D’Alenya 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'fvmg', false, null, null, null, now()),
  ('L ATELIER DU MANGEUR D OMBRES', 'Divertissement', '23 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Divertissement.', 'directory', 'l-atelier-du-mangeur-d-ombres', false, null, null, null, now()),
  ('Les comptoirs du cordonnier', 'Services', '1 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'les-comptoirs-du-cordonnier', false, null, null, null, now()),
  ('Les Pains du Soleil', 'Alimentation', 'Bd Jacques Albert, 66200 Elne', '+33 4 68 68 04 24', 'https://www.lespainsdusoleil.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'les-pains-du-soleil', false, null, null, null, now()),
  ('Marie Blachère', 'Alimentation', 'Boulevard Jacques Albert, 66200 Elne', null, 'https://www.marieblachere.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'marie-blachere', false, null, null, null, now()),
  ('OPTICIEN POUR TOUS', 'Services', '9 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'opticien-pour-tous', false, null, null, null, now()),
  ('Picard', 'Services', '66200 Elne', '+33 4 68 37 71 39', 'https://magasins.picard.fr/1240-picard-elne', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'picard', false, null, null, null, now()),
  ('PROVENC''HALLES', 'Alimentation', 'Route D''Alenya Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'provenc-halles', false, null, null, null, now()),
  ('RAPHALEX', 'Alimentation', 'Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'raphalex', false, null, null, null, now()),
  ('Roc-Eclerc', 'Services', '4 Boulevard Jacques Albert, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'roc-eclerc', false, null, null, null, now()),
  ('SOCIETE GENERALE (SG)', 'Services', '19 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'societe-generale-sg', false, null, null, null, now()),
  ('Société Générale', 'Services', '19 Boulevard Jacques Albert, 66200 Elne', '+33 4 68 81 85 26', 'https://agences.sg.fr/banque-assurance/particulier/agence-elne-id3000304037', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'societe-generale', false, null, null, null, now()),
  ('SOLEIL 09', 'Services', '8 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'soleil-09', false, null, null, null, now()),
  ('SUSHI MARKET', 'Restaurants', 'Intermarche 10 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'sushi-market', false, null, null, null, now()),
  ('TESSOPER', 'Services', '10 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'tessoper', false, null, null, null, now()),
  ('ZUEGG SPA', 'Alimentation', '2 Boulevard Jacques Albert 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'zuegg-spa', false, null, null, null, now()),
  ('2 mèches avec Carla', 'Santé & bien-être', '66200 Elne', '+33 9 80 94 70 23', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', '2-meches-avec-carla', false, null, null, null, now()),
  ('Action vape', 'Services', '66200 Elne', '+33 4 68 66 64 69', 'https://www.actionvape.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'action-vape', false, null, null, null, now()),
  ('Al Campanar', 'Services', '5 Place de l''Église, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'al-campanar', false, null, null, null, now()),
  ('Aldi', 'Alimentation', '2 Rue Pierre Curiezai, 66200 Elne', null, 'https://www.aldi.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'aldi', false, null, null, null, now()),
  ('Allianz', 'Services', '17 Boulevard des Evadés de France, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'allianz', false, null, null, null, now()),
  ('Au Remp''Arts', 'Restaurants', '3 Place du Colonel Charles Roger, 66200 Elne', '+33 4 68 22 31 95', 'http://www.remparts.fr/restaurant', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'au-remp-arts', false, null, null, null, now()),
  ('Banque Populaire', 'Services', '66200 Elne', '+33 4 68 08 44 33', 'https://agences.banquepopulaire.fr/banque-assurance/agence-elne-id1660700002', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'banque-populaire', false, null, null, null, now()),
  ('Biocoop', 'Alimentation', '1, 66200 Elne', null, 'https://www.biocoop.fr/magasins-bio/Trouver-mon-magasin-Biocoop/Occitanie2/Pyrenees-Orientales/BIOCOOP-D-ELNE', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'biocoop', false, null, null, null, now()),
  ('BNP Paribas', 'Services', '22 Boulevard Voltaire, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'bnp-paribas', false, null, null, null, now()),
  ('Caisse d''Épargne', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'caisse-d-epargne', false, null, null, null, now()),
  ('Carrefour City', 'Services', '35 Boulevard Voltaire, 66200 Elne', '+33 4 68 07 65 15', 'https://www.carrefour.fr/magasin/carrefour-city-elne-voltaire', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'carrefour-city', false, null, null, null, now()),
  ('Centrakor', 'Services', '16 Rue Nicolas Appert, 66200 Elne', '+33 4 68 28 72 38', 'https://www.centrakor.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'centrakor', false, null, null, null, now()),
  ('Centre médical', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'centre-medical', false, null, null, null, now()),
  ('Century 21', 'Services', '4 bis Rue du Marche, 66200 Elne', '+33 4 68 64 41 28', 'https://www.century21-carre-as-elne.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'century-21', false, null, null, null, now()),
  ('Chez CriCri', 'Restaurants', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'chez-cricri', false, null, null, null, now()),
  ('CIC', 'Services', '66200 Elne', '+33 4 68 34 00 88', 'https://www.cic.fr/fr/agence/occitanie/pyrenees-orientales/10057-19283-00', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'cic', false, null, null, null, now()),
  ('Coiffure Daniel', 'Santé & bien-être', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'coiffure-daniel', false, null, null, null, now()),
  ('Crédit Agricole', 'Services', '66200 Elne', '+33 4 68 68 87 70', 'https://www.credit-agricole.fr/particulier/agence/sud-mediterranee/agence-d-elne-2129.html', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'credit-agricole', false, null, null, null, now()),
  ('Cuisine & Co', 'Maison', '66200 Elne', '+33 6 67 71 49 14', 'https://www.clcuisinesandco.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Maison.', 'directory', 'cuisine-co', false, null, null, null, now()),
  ('Cycles et scooters Colomines', 'Sports & activités', '37 Avenue Paul Reig, 66200 Elne', '+33468220715', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Sports & activités.', 'directory', 'cycles-et-scooters-colomines', false, null, null, null, now()),
  ('Delbard', 'Maison', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Maison.', 'directory', 'delbard', false, null, null, null, now()),
  ('Dietplus', 'Santé & bien-être', '66200 Elne', null, 'https://www.dietplus.fr/centres/elne/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'dietplus', false, null, null, null, now()),
  ('DV Immo', 'Services', '66200 Elne', '+33 4 68 95 18 11', 'https://www.dv-immobilier-international.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'dv-immo', false, null, null, null, now()),
  ('Dyneff', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'dyneff', false, null, null, null, now()),
  ('El Racó d’Elna', 'Restaurants', '66200 Elne', '+33 6 77 97 81 26', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'el-raco-delna', false, null, null, null, now()),
  ('Elne Voyage', 'Escapades', '17 Boulevard des Evades de France, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Escapades.', 'directory', 'elne-voyage', false, null, null, null, now()),
  ('Folies Chauss', 'Vêtements & mode', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Vêtements & mode.', 'directory', 'folies-chauss', false, null, null, null, now()),
  ('Generali', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'generali', false, null, null, null, now()),
  ('Guy Hoquet', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'guy-hoquet', false, null, null, null, now()),
  ('HK Food', 'Restaurants', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'hk-food', false, null, null, null, now()),
  ('Idea', 'Restaurants', '66200 Elne', '+33 9 83 29 47 37', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'idea', false, null, null, null, now()),
  ('Illiberis Fleurs', 'Services', '66200 Elne', '+33 4 68 22 59 88', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'illiberis-fleurs', false, null, null, null, now()),
  ('Intermarché', 'Services', '10, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'intermarche', false, null, null, null, now()),
  ('Intermarché Super', 'Alimentation', '10, 66200 Elne', '+33 4 68 22 04 56', 'https://www.intermarche.com/magasins/06829/elne-66200/infos-pratiques', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'intermarche-super', false, null, null, null, now()),
  ('L''étoile', 'Restaurants', '66200 Elne', '+33 6 19 62 26 75', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'l-etoile', false, null, null, null, now()),
  ('La Casa d''Elna', 'Restaurants', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'la-casa-d-elna', false, null, null, null, now()),
  ('La Recyclerie', 'Maison', '15 Boulevard d''Archimède, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Maison.', 'directory', 'la-recyclerie', false, null, null, null, now()),
  ('Le Jardin', 'Restaurants', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'le-jardin', false, null, null, null, now()),
  ('Les bouquets du bonheur', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'les-bouquets-du-bonheur', false, null, null, null, now()),
  ('Les Opticiens Perrin', 'Santé & bien-être', '2 bis Rue des Pommiers, 66200 Elne', '+33 4 68 22 10 14', 'http://opticiensperrin.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'les-opticiens-perrin', false, null, null, null, now()),
  ('Les Pains d''Adrien', 'Alimentation', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'les-pains-d-adrien', false, null, null, null, now()),
  ('Lidl', 'Alimentation', '1, 66200 Elne', null, 'https://www.lidl.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'lidl', false, null, null, null, now()),
  ('Mangeons Frais', 'Alimentation', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'mangeons-frais', false, null, null, null, now()),
  ('Marie Max', 'Services', '66200 Elne', '+33 4 68 22 75 99', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'marie-max', false, null, null, null, now()),
  ('Marée Catalane', 'Alimentation', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Alimentation.', 'directory', 'maree-catalane', false, null, null, null, now()),
  ('Midas', 'Services', '16 Rue Nicolas Appert, 66200 Elne', '+33 4 48 22 05 39', 'https://www.midas.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'midas', false, null, null, null, now()),
  ('Mister Kebab', 'Restaurants', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'mister-kebab', false, null, null, null, now()),
  ('New''s Coffee', 'Restaurants', '66200 Elne', '+33 4 34 12 26 12', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Restaurants.', 'directory', 'new-s-coffee', false, null, null, null, now()),
  ('Optic 2000', 'Santé & bien-être', '114 Avenue Narcisse Planas, 66200 Elne', '+33 4 68 87 04 07', 'https://www.optic2000.com/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'optic-2000', false, null, null, null, now()),
  ('Pharmacie Clotis', 'Santé & bien-être', '66200 Elne', '+33468220873', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'pharmacie-clotis', false, null, null, null, now()),
  ('Pharmacie Croix Verte', 'Santé & bien-être', 'Avenue Narcisse Planas, 66200 Elne', '+33 4 68 22 06 25', 'https://www.pharmacie-la-croix-verte.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'pharmacie-croix-verte', false, null, null, null, now()),
  ('Pharmacie Épicentre', 'Santé & bien-être', '17 Boulevard des Évadés, 66200 Elne', '+33 4 68 22 10 64', 'https://pharmacieepicentre-elne.pharmavie.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'pharmacie-epicentre', false, null, null, null, now()),
  ('Point P', 'Maison', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Maison.', 'directory', 'point-p', false, null, null, null, now()),
  ('Pompes Funèbres JC Palotis', 'Services', '27 Route de Latour Bas Elne, 66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'pompes-funebres-jc-palotis', false, null, null, null, now()),
  ('Pressing', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'pressing', false, null, null, null, now()),
  ('Pôle Vert', 'Maison', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Maison.', 'directory', 'pole-vert', false, null, null, null, now()),
  ('Renault', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'renault', false, null, null, null, now()),
  ('Rural Master', 'Services', '66200 Elne', '+33 4 68 22 32 32', null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'rural-master', false, null, null, null, now()),
  ('Select Assur 66', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'select-assur-66', false, null, null, null, now()),
  ('Tchip', 'Santé & bien-être', '66200 Elne', '+33 4 48 07 21 50', 'https://tchip.fr/salon/view/2965', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Santé & bien-être.', 'directory', 'tchip', false, null, null, null, now()),
  ('Terroir Catalan', 'Services', '66200 Elne', '+33 4 34 12 35 39', 'https://terroir-catalan.fr/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'terroir-catalan', false, null, null, null, now()),
  ('Terroirs Romans', 'Vins & spiritueux', '66200 Elne', '+33 4 68 95 15 74', 'https://www.terrassous.com/les-boutiques-terrassous/', null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Vins & spiritueux.', 'directory', 'terroirs-romans', false, null, null, null, now()),
  ('UTILBOX', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'utilbox', false, null, null, null, now()),
  ('Épicentre', 'Services', '66200 Elne', null, null, null, 'Commerce local référencé à Elne via OpenStreetMap et la base Sirene. Catégorie : Services.', 'directory', 'epicentre', false, null, null, null, now());

-- 3) Vérification
select count(*) as total_commerces_elne, category, count(*) over (partition by category) as par_categorie
  from public.merchants
  group by category, id
  order by category, name;

commit;